#!/usr/bin/env python
""" Test application to exercise STDIN, STDOUT, and STDERR.

"""
from argparse import ArgumentParser
from os import environ
from sys import stdin, stderr, stdout


def main() -> int:
    """ Echo the contents of STDIN to STDOUT.

    :return: system exit code
    """
    parser = ArgumentParser()
    parser.add_argument("-e", "--env", help="display environment variable")
    args = parser.parse_args()
    if args.env:
        stderr.write(f"{args.env}={environ.get(args.env, '')}\n")
    stdout.buffer.write(stdin.buffer.read())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
