@startuml

' The accompanying image was created using the "PlantUML Integration" plugin:
' <https://plugins.jetbrains.com/plugin/7017-plantuml-integration>

title httpexec System Architecture

node "REST Client" as client {
    ' Remote clients using the REST API.
}

node "Local Host" {
    ' Server where httpexec is running.
	component "httpexec" as httpexec
    component "Web Server" as server
	component "Command" as command
}

server .right. client : HTTP
server -down- httpexec : ASGI
httpexec -right- command : CLI

@enduml
