---
name: Publish - Test PyPI

on:
  push:
    branches:
      # Verify new releases test.pypi.org before pushing to 'main'.
      - dev
  workflow_dispatch:  # allow manual trigger via the GitHub UI

jobs:
  publish:
    name: Build packages and publish to Test PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi-test
      url: https://test.pypi.org/project/httpexec
    permissions:
      id-token: write  # needed for OIDC trusted publishing
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"  # latest avilable version
      - name: Install application and its dependencies
        run: python -m pip install ".[dev]"
      - name: Build packages
        run: python -m build --sdist --wheel --outdir=dist/ .
      - name: Run tests
        run: |
          python -m pytest tests/
          python -m twine check dist/*
      - name: Publish packages to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/
