---
name: Publish

on:
  # TODO: Disable automatic triggers until more experience is gained with this.
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # manual trigger via the GitHub UI

jobs:
  publish:
    name: Build packages and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/httpexec
    permissions:
      id-token: write  # needed for OIDC trusted publishing
    steps:
      - name: Check out project
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.X"  # latest avilable version
      - name: Install application and its dependencies
        run: python -m pip install ".[dev]"
      - name: Build packages
        run: python -m build --sdist --wheel --outdir=dist/ .
      - name: Run tests
        run: |
          python -m pytest tests/
          python -m twine check dist/*
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
