name: Test

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
    steps:
      - name: Check out project
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -U pip -r requirements.txt -r tests/requirements.txt
      - name: Install application
        run: python -m pip install .
      - name: Run tests
        run: python -m pytest tests/httpexec
